# Generated by Django 5.0.6 on 2024-06-01 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=40, verbose_name='Nível')),
            ],
            options={
                'verbose_name': 'Nível',
                'verbose_name_plural': 'Níveis',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('time', models.IntegerField(help_text='Tempo em segundos')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_players', related_query_name='player_category', to='game.category', verbose_name='Categoria')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_levels', related_query_name='player_level', to='game.level', verbose_name='Nível')),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playes', to=settings.AUTH_USER_MODEL, verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=255, verbose_name='Questão')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', related_query_name='question_category', to='game.category', verbose_name='Categoria')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', related_query_name='question_level', to='game.level', verbose_name='Nível')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=255, verbose_name='Resposta')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correcta')),
                ('quetion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', related_query_name='question_answer', to='game.question', verbose_name='Questão')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
    ]
