# Generated by Django 5.0.6 on 2024-06-12 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_text', models.CharField(max_length=40, verbose_name='Nível')),
            ],
            options={
                'verbose_name': 'Nével',
                'verbose_name_plural': 'Níveis',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Questão')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.category', verbose_name='Categoria')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.difficulty', verbose_name='Nível')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(max_length=255, verbose_name='Resposta')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correcta')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.question', verbose_name='Questão')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
        migrations.CreateModel(
            name='QuizUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Jogador')),
                ('total_score', models.DecimalField(decimal_places=2,default=0, max_digits=10, verbose_name='Total de Pontos')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0, help_text='Tempo em segundos')),
                ('is_correct', models.BooleanField(verbose_name='Correcta', default=False,)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.category', verbose_name='Categoria')),
                ('answer',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='game.answer', verbose_name='Resposta')),
                ('question',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='game.question',verbose_name='Questão')),
                ('quiz_user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='game.quizuser',verbose_name='Questão')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.difficulty', verbose_name='Nível')),
                
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
            },
        ),
    ]
