# Generated by Django 5.0.6 on 2024-06-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_result_answer_alter_result_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuser',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total de Pontos'),
        ),
    ]
