# Generated by Django 5.0.6 on 2024-06-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_quizuser_total_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(null=True, verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Regra',
                'verbose_name_plural': 'Regras',
            },
        ),
    ]
