# Generated by Django 5.0.6 on 2024-06-16 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField(null=True, verbose_name='Conceitos')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Conteúdo')),
                ('extra', models.CharField(blank=True, max_length=255, null=True, verbose_name='Info')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='link')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Definição',
                'verbose_name_plural': 'Definições',
            },
        ),
    ]
