# Generated by Django 5.0.6 on 2024-06-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_result_pub_date_settings_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='total_time',
            field=models.IntegerField(default=0, help_text='Tempo em segundos', verbose_name='Tempo'),
        ),
    ]
