# Generated by Django 5.0.6 on 2024-05-23 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=255, verbose_name='Resposta')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correcta')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=True)),
                ('level_name', models.CharField(max_length=40, verbose_name='Nível')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('score', models.IntegerField()),
                ('time', models.IntegerField()),
                ('answer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='player_answer', to='game.answer', verbose_name='Resposta')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=255, verbose_name='Questão')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', related_query_name='question_category', to='game.category', verbose_name='Categoria')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', related_query_name='question_level', to='game.level', verbose_name='Nível')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='quetion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', related_query_name='question_answer', to='game.question', verbose_name='Questão'),
        ),
    ]
